[tool.poetry]
name = "{{cookiecutter.project_slug}}"
version = "{{cookiecutter.project_version}}"
description = "{{cookiecutter.project_short_description}}"
authors = ["{{cookiecutter.full_name}} <{{cookiecutter.email}}>"]
license = "GPLv3"

[tool.poetry.dependencies]
python = "^{{cookiecutter.python_min_version}}"
{%- if cookiecutter.command_line_interface|lower == 'click' %}
click = "^8.0.1"
{%- endif %}
rich = "^10.12.0"

[tool.poetry.dev-dependencies]
black = "^21.7b0"
pytest = "^6.2.4"
wheel = "^0.37.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
