[tool.poetry]
name = "{{cookiecutter.project_slug}}"
version = "{{cookiecutter.project_version}}"
description = "{{cookiecutter.project_short_description}}"
authors = ["{{cookiecutter.full_name}} <{{cookiecutter.email}}>"]
license = "GPLv3"

[tool.poetry.dependencies]
python = "^{{cookiecutter.python_min_version}}"

[tool.poetry.dev-dependencies]
black = "^21.7b0"
coverage = "^5.5"
pytest = "^6.2.4"
pytest-runner = "^5.3.1"
wheel = "^0.37.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
